version: "3.5"

services:
  nginx: # Only for local test
    image: "typing_scratch_bldg_nginx_dev:0.1.0"
    container_name: "typing_scratch_bldg_nginx_dev"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "16444:80"
    volumes:
      - ./htdocs/:/usr/share/nginx/html
    networks:
      - typing_scratch_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  api:
    image: "typing_scratch_bldg_api_dev:1.0.0"
    container_name: "typing_scratch_bldg_api_dev"
    depends_on:
      - db
      - nginx
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "15444:8000"
    volumes:
      - ./app:/usr/src/app/app:cached
      - ./scripts:/usr/src/app/scripts:cached
      - ./htdocs:/usr/src/app/htdocs:cached
      - ./db:/usr/src/app/db:cached
    working_dir: /usr/src/app/scripts
    command: bash -c "./init_db.sh && ./run_server.sh"
    # tty: true
    networks:
      - typing_scratch_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development
  db:
    image: "typing_scratch_bldg_db_dev:0.1.0"
    container_name: "typing_scratch_bldg_db_dev"
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    restart: always
    tty: true
    # expose:
    #   - "3306"
    ports:
      - "17444:3306"
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d:cached
      - ./docker/db/conf.d:/etc/mysql/conf.d:cached
      - ./log/db:/var/log/mysql:cached
    networks:
      - typing_scratch_network
    environment:
      APP_ENV: "development"
      TZ: "Asia/Tokyo"
    env_file:
      - .env.development

networks:
  default:
    external:
      name: bridge
  typing_scratch_network:
    name: typing_scratch_network
    driver: bridge
    external: true
